import BlithCore
import SceneKit
import SwiftUI
import UIKit

// MARK: - Model

/// The 3D figure, generated by `design/body3d/build_body.py` from BodyParts3D (skin) and Z-Anatomy
/// (muscles), both CC BY-SA; see `design/body3d/LICENSE-ASSETS.md`.
///
/// `body.bin` (format BLB3) holds two layers that share one coordinate space (metres, y up, feet on
/// y = 0, facing +z, the person's left at +x):
/// - `skin`: one geometry element per `BodyRegion`, so tapping returns the region directly and notes
///   stay anchored to regions, never to screen points.
/// - `muscle`: an underlayer (one element per region, no muscle) that keeps the figure continuous,
///   then one element per named muscle. Every triangle also carries its `BodyRegion`.
///
/// Layout (little endian): "BLB3", u32 layerCount, then per layer: u32 vertexCount, triangleCount,
/// groupCount; float3 positions; float3 normals; groups of (u32 region, u32 muscle or 0xFFFFFFFF,
/// u32 firstTriangle, u32 triangleCount); u8 region per triangle, padded to 4 bytes; u32 indices.
final class Body3DModel {
    struct Region: Decodable {
        let id: String
        let anchor: [Float]
        let normal: [Float]
        let radius: Float
    }

    /// A named muscle (or tendon / aponeurosis) instance, e.g. "Gastrocnemius (medial head)", right side.
    struct Muscle: Decodable {
        let id: String
        let name: String
        /// "left", "right" or "midline".
        let side: String
        /// "muscle" or "tendon".
        let kind: String
        /// The `BodyRegion` raw value this muscle mostly lies in.
        let region: String
        let anchor: [Float]
        let normal: [Float]

        var bodyRegion: BodyRegion? { BodyRegion(rawValue: region) }
    }

    struct Meta: Decodable {
        let height: Float
        let regions: [Region]
        let muscles: [Muscle]
        let attribution: String?
        let license: String?
    }

    struct Group {
        /// Index into `meta.regions`.
        let region: Int
        /// Index into `meta.muscles`; nil for skin and underlayer groups.
        let muscle: Int?
        let firstTriangle: Int
        let count: Int
    }

    struct Layer {
        let geometry: SCNGeometry
        let groups: [Group]
        /// Index into `meta.regions` for every triangle of the layer.
        let triangleRegion: [UInt8]
    }

    let meta: Meta
    let skin: Layer
    let muscle: Layer

    static let shared: Body3DModel? = Body3DModel()

    private init?() {
        guard let binURL = Bundle.main.url(forResource: "body", withExtension: "bin"),
              let jsonURL = Bundle.main.url(forResource: "body3d", withExtension: "json"),
              let data = try? Data(contentsOf: binURL, options: .mappedIfSafe),
              let json = try? Data(contentsOf: jsonURL),
              let meta = try? JSONDecoder().decode(Meta.self, from: json),
              data.count > 8, String(data: data.prefix(4), encoding: .ascii) == "BLB3" else { return nil }
        var offset = 8
        guard Self.u32(data, 4) >= 2,
              let skin = Self.readLayer(data, &offset),
              let muscle = Self.readLayer(data, &offset) else { return nil }
        self.meta = meta
        self.skin = skin
        self.muscle = muscle
    }

    private static func u32(_ data: Data, _ offset: Int) -> Int {
        Int(data.subdata(in: offset..<offset + 4).withUnsafeBytes { $0.loadUnaligned(as: UInt32.self) }.littleEndian)
    }

    private static func readLayer(_ data: Data, _ offset: inout Int) -> Layer? {
        guard data.count >= offset + 12 else { return nil }
        let v = u32(data, offset), t = u32(data, offset + 4), g = u32(data, offset + 8)
        var o = offset + 12
        let posOffset = o; o += v * 12
        let nrmOffset = o; o += v * 12
        guard data.count >= o + g * 16 else { return nil }
        var groups: [Group] = []
        for i in 0..<g {
            let b = o + i * 16
            let m = u32(data, b + 4)
            groups.append(Group(region: u32(data, b), muscle: m == 0xFFFF_FFFF ? nil : m,
                                firstTriangle: u32(data, b + 8), count: u32(data, b + 12)))
        }
        o += g * 16
        guard data.count >= o + t else { return nil }
        let triangleRegion = [UInt8](data.subdata(in: o..<o + t))
        o += t + (4 - t % 4) % 4
        let indexOffset = o
        o += t * 12
        guard data.count >= o else { return nil }

        let positions = SCNGeometrySource(data: data.subdata(in: posOffset..<posOffset + v * 12), semantic: .vertex, vectorCount: v,
                                          usesFloatComponents: true, componentsPerVector: 3, bytesPerComponent: 4, dataOffset: 0, dataStride: 12)
        let normals = SCNGeometrySource(data: data.subdata(in: nrmOffset..<nrmOffset + v * 12), semantic: .normal, vectorCount: v,
                                        usesFloatComponents: true, componentsPerVector: 3, bytesPerComponent: 4, dataOffset: 0, dataStride: 12)
        let elements = groups.map { grp in
            let start = indexOffset + grp.firstTriangle * 12
            return SCNGeometryElement(data: data.subdata(in: start..<start + grp.count * 12), primitiveType: .triangles,
                                      primitiveCount: grp.count, bytesPerIndex: 4)
        }
        offset = o
        return Layer(geometry: SCNGeometry(sources: [positions, normals], elements: elements), groups: groups,
                     triangleRegion: triangleRegion)
    }

    func regionIndex(_ region: BodyRegion) -> Int? { meta.regions.firstIndex { $0.id == region.rawValue } }

    func muscleIndex(_ muscle: Muscle) -> Int? { meta.muscles.firstIndex { $0.id == muscle.id } }

    /// Region and muscle under a hit on `layer`: element index and face index within that element.
    func lookup(_ layer: Layer, element: Int, face: Int) -> (BodyRegion, Muscle?)? {
        guard layer.groups.indices.contains(element) else { return nil }
        let group = layer.groups[element]
        let tri = group.firstTriangle + face
        let r = layer.triangleRegion.indices.contains(tri) ? Int(layer.triangleRegion[tri]) : group.region
        guard meta.regions.indices.contains(r), let region = BodyRegion(rawValue: meta.regions[r].id) else { return nil }
        let muscle = group.muscle.flatMap { meta.muscles.indices.contains($0) ? meta.muscles[$0] : nil }
        return (region, muscle)
    }

    func info(for region: BodyRegion) -> Region? { meta.regions.first { $0.id == region.rawValue } }
}

extension Array where Element == Float {
    var vector: SCNVector3 { count >= 3 ? SCNVector3(self[0], self[1], self[2]) : SCNVector3Zero }
}

// MARK: - Scene

enum BodyLayer: String, CaseIterable, Identifiable {
    case skin, muscle
    var id: String { rawValue }
    var title: String { self == .skin ? "Figure" : "Muscles" }
}

/// Owns the SceneKit scene and all camera moves. Rotation is a turntable around the body's
/// vertical axis; zoom moves the camera toward a target point on the body.
@MainActor
final class BodySceneController: NSObject {
    let scene = SCNScene()
    let model: Body3DModel
    let turntable = SCNNode()
    /// Glass figure (skin layer).
    let skinNode: SCNNode
    /// Anatomical muscles (muscle layer). Only the node of the current layer is visible.
    let muscleNode: SCNNode
    let cameraNode = SCNNode()
    let rig = SCNNode()
    let keyLight = SCNNode()
    let markers = SCNNode()
    weak var view: SCNView?

    var layer: BodyLayer = .skin
    private(set) var yaw: Float = 0
    private(set) var distance: Float = 3.9
    private var target = SCNVector3(0, 0.93, 0)
    private var skinMaterials: [SCNMaterial] = []
    private var muscleMaterials: [SCNMaterial] = []
    private let ambientLight = SCNLight()
    private let rimLight = SCNLight()
    var onSelect: ((BodyRegion, Body3DModel.Muscle?) -> Void)?
    var onMarker: ((String) -> Void)?

    static let fullDistance: Float = 3.9
    static let fullTarget = SCNVector3(0, 0.93, 0)

    init(model: Body3DModel) {
        self.model = model
        skinNode = SCNNode(geometry: model.skin.geometry.copy() as? SCNGeometry)
        muscleNode = SCNNode(geometry: model.muscle.geometry.copy() as? SCNGeometry)
        super.init()
        build()
    }

    private func build() {
        scene.background.contents = UIColor.clear
        skinMaterials = model.skin.groups.map { _ in Self.skinMaterial() }
        muscleMaterials = model.muscle.groups.map { group in
            guard let m = group.muscle, model.meta.muscles.indices.contains(m) else { return Self.muscleMaterial(color: Self.underlayerColor) }
            return Self.muscleMaterial(color: Self.tone(for: model.meta.muscles[m]))
        }
        skinNode.geometry?.materials = skinMaterials
        muscleNode.geometry?.materials = muscleMaterials
        turntable.addChildNode(skinNode)
        turntable.addChildNode(muscleNode)
        turntable.addChildNode(markers)
        scene.rootNode.addChildNode(turntable)
        scene.rootNode.addChildNode(floorNode())

        let camera = SCNCamera()
        camera.fieldOfView = 30
        camera.zNear = 0.05
        camera.zFar = 30
        camera.wantsHDR = true
        camera.bloomIntensity = 0.55
        camera.bloomThreshold = 0.6
        camera.bloomBlurRadius = 10
        camera.screenSpaceAmbientOcclusionRadius = 0.035
        cameraNode.camera = camera
        rig.addChildNode(cameraNode)
        scene.rootNode.addChildNode(rig)

        let ambient = SCNNode()
        ambientLight.type = .ambient
        ambient.light = ambientLight
        scene.rootNode.addChildNode(ambient)

        keyLight.light = SCNLight()
        keyLight.light?.type = .directional
        keyLight.light?.intensity = 900
        keyLight.light?.color = UIColor(hex: 0xDCE6FF)
        keyLight.eulerAngles = SCNVector3(-0.5, -0.6, 0)
        scene.rootNode.addChildNode(keyLight)

        let rim = SCNNode()
        rimLight.type = .directional
        rim.light = rimLight
        rim.eulerAngles = SCNVector3(-0.2, .pi * 0.85, 0)
        scene.rootNode.addChildNode(rim)
        setLayer(.skin)
        applyCamera(animated: false)
    }

    static let fresnel = """
    float3 n = normalize(_surface.normal);
    float3 v = normalize(-_surface.position);
    float f = pow(1.0 - saturate(dot(n, v)), 2.2);
    """

    /// Luminous cobalt glass: deep #1B3A8C in shadow, #4F8EFF where lit, an ice (#B9DAFF) Fresnel
    /// rim, slightly translucent (front-most layer only, so the figure never shows its own inside).
    static func skinMaterial() -> SCNMaterial {
        let m = SCNMaterial()
        m.lightingModel = .lambert
        m.diffuse.contents = UIColor(hex: 0x4F8EFF)
        m.emission.contents = UIColor(hex: 0x10265E)
        m.transparency = 0.9
        m.transparencyMode = .singleLayer
        m.setValue(Float(0), forKey: "highlight")
        m.shaderModifiers = [
            .fragment: """
            #pragma arguments
            float highlight;
            #pragma body
            \(fresnel)
            _output.color.rgb += float3(0.725, 0.855, 1.0) * f * 1.15;
            _output.color.rgb += float3(0.49, 0.70, 1.0) * highlight * (0.08 + 0.32 * f);
            """,
        ]
        return m
    }

    static let tendonColor = UIColor(hex: 0x93403F)
    static let underlayerColor = UIColor(hex: 0x74191E)

    /// Deep tissue red (#9C2328) with a small, stable per-muscle variation so neighbours separate.
    static func tone(for muscle: Body3DModel.Muscle) -> UIColor {
        if muscle.kind == "tendon" { return tendonColor }
        var h: UInt32 = 2_166_136_261
        for b in muscle.name.utf8 { h = (h ^ UInt32(b)) &* 16_777_619 }
        let k = 0.93 + CGFloat(h % 1000) / 1000 * 0.14
        return UIColor(red: min(1, 0.612 * k), green: 0.137 * k, blue: 0.157 * k, alpha: 1)
    }

    static func muscleMaterial(color: UIColor) -> SCNMaterial {
        let m = SCNMaterial()
        m.lightingModel = .blinn
        m.diffuse.contents = color
        m.specular.contents = UIColor(white: 0.2, alpha: 1)
        m.shininess = 0.3
        m.setValue(Float(0), forKey: "highlight")
        m.shaderModifiers = [
            .fragment: """
            #pragma arguments
            float highlight;
            #pragma body
            \(fresnel)
            _output.color.rgb += float3(1.0, 0.42, 0.36) * f * 0.16;
            _output.color.rgb += (_output.color.rgb * 0.22 + float3(0.49, 0.70, 1.0) * f * 0.35) * highlight;
            """,
        ]
        return m
    }

    func floorNode() -> SCNNode {
        let size = 256
        let img = UIGraphicsImageRenderer(size: CGSize(width: size, height: size)).image { ctx in
            let colors = [UIColor(hex: 0x4C8DFF, alpha: 0.55).cgColor, UIColor(hex: 0x4C8DFF, alpha: 0.12).cgColor, UIColor.clear.cgColor] as CFArray
            let g = CGGradient(colorsSpace: CGColorSpaceCreateDeviceRGB(), colors: colors, locations: [0, 0.45, 1])!
            let c = CGPoint(x: size / 2, y: size / 2)
            ctx.cgContext.drawRadialGradient(g, startCenter: c, startRadius: 0, endCenter: c, endRadius: CGFloat(size) / 2, options: [])
            UIColor(hex: 0x3DDCFF, alpha: 0.5).setStroke()
            for r in [0.3, 0.42] {
                let rr = CGFloat(size) * r
                ctx.cgContext.setLineWidth(1.5)
                ctx.cgContext.strokeEllipse(in: CGRect(x: c.x - rr, y: c.y - rr, width: rr * 2, height: rr * 2))
            }
        }
        let plane = SCNPlane(width: 1.5, height: 1.5)
        let m = SCNMaterial()
        m.lightingModel = .constant
        m.diffuse.contents = img
        m.isDoubleSided = true
        m.writesToDepthBuffer = false
        m.blendMode = .add
        plane.materials = [m]
        let node = SCNNode(geometry: plane)
        node.eulerAngles.x = -.pi / 2
        node.position.y = 0.002
        return node
    }

    // MARK: Layer and highlight

    func setLayer(_ layer: BodyLayer) {
        self.layer = layer
        skinNode.isHidden = layer != .skin
        muscleNode.isHidden = layer != .muscle
        if layer == .skin {
            ambientLight.intensity = 260
            ambientLight.color = UIColor(hex: 0x9FB4FF)
            rimLight.intensity = 500
            rimLight.color = UIColor(hex: 0x3DDCFF)
            cameraNode.camera?.screenSpaceAmbientOcclusionIntensity = 0
            cameraNode.camera?.bloomIntensity = 0.55
            cameraNode.camera?.bloomThreshold = 0.6
        } else {
            ambientLight.intensity = 300
            ambientLight.color = UIColor(hex: 0xFFE9E4)
            rimLight.intensity = 380
            rimLight.color = UIColor(hex: 0xFFC2B8)
            cameraNode.camera?.screenSpaceAmbientOcclusionIntensity = 0.9
            // Less bloom on the muscles: no red halo around the figure.
            cameraNode.camera?.bloomIntensity = 0.2
            cameraNode.camera?.bloomThreshold = 0.85
        }
    }

    /// Highlights a region on both layers. On the muscle layer a given muscle is highlighted on its
    /// own; without one, the region's underlayer and the muscles that mostly lie in it light up.
    func highlight(_ region: BodyRegion?, muscle: Body3DModel.Muscle? = nil) {
        for m in skinMaterials + muscleMaterials { m.setValue(Float(0), forKey: "highlight") }
        let r = region.flatMap(model.regionIndex)
        if let r {
            for (i, g) in model.skin.groups.enumerated() where g.region == r { skinMaterials[i].setValue(Float(1), forKey: "highlight") }
        }
        if let muscle, let mi = model.muscleIndex(muscle) {
            for (i, g) in model.muscle.groups.enumerated() where g.muscle == mi { muscleMaterials[i].setValue(Float(1), forKey: "highlight") }
        } else if let r {
            for (i, g) in model.muscle.groups.enumerated() where g.region == r { muscleMaterials[i].setValue(Float(1), forKey: "highlight") }
        }
    }

    // MARK: Camera

    func applyCamera(animated: Bool, duration: Double = 0.8) {
        SCNTransaction.begin()
        SCNTransaction.animationDuration = animated ? duration : 0
        SCNTransaction.animationTimingFunction = CAMediaTimingFunction(controlPoints: 0.23, 1, 0.32, 1)
        turntable.eulerAngles.y = yaw
        rig.position = target
        cameraNode.position = SCNVector3(0, 0.05 * distance / Self.fullDistance, distance)
        cameraNode.eulerAngles = SCNVector3(-0.012, 0, 0)
        SCNTransaction.commit()
    }

    func rotate(by delta: Float) {
        yaw += delta
        turntable.eulerAngles.y = yaw
    }

    func setYaw(_ value: Float, animated: Bool = true) {
        var d = (value - yaw).truncatingRemainder(dividingBy: 2 * .pi)
        if d > .pi { d -= 2 * .pi }
        if d < -.pi { d += 2 * .pi }
        yaw += d
        applyCamera(animated: animated)
    }

    func zoom(by factor: Float, animated: Bool = false) {
        distance = max(0.7, min(Self.fullDistance, distance / factor))
        if distance > Self.fullDistance * 0.92 { target = Self.fullTarget }
        applyCamera(animated: animated, duration: 0.35)
    }

    func reset(animated: Bool = true) {
        distance = Self.fullDistance
        target = Self.fullTarget
        highlight(nil)
        applyCamera(animated: animated)
    }

    /// Turn the region toward the viewer and frame it.
    func focus(_ region: BodyRegion, animated: Bool = true) {
        guard let info = model.info(for: region) else { return }
        let n = info.normal.vector
        let facing = abs(n.x) + abs(n.z) > 0.2 ? -atan2(n.x, n.z) : yaw
        var d = (facing - yaw).truncatingRemainder(dividingBy: 2 * .pi)
        if d > .pi { d -= 2 * .pi }
        if d < -.pi { d += 2 * .pi }
        yaw += d
        let a = info.anchor.vector
        let c = cos(yaw), s = sin(yaw)
        target = SCNVector3(a.x * c + a.z * s, a.y, -a.x * s + a.z * c)
        distance = max(1.35, min(2.6, info.radius * 9))
        highlight(region)
        applyCamera(animated: animated, duration: 0.9)
    }

    // MARK: Markers

    func setMarkers(_ notes: [HealthEvent], focused: String?, today: LocalDate) {
        markers.childNodes.forEach { $0.removeFromParentNode() }
        var perRegion: [BodyRegion: Int] = [:]
        for note in notes {
            guard let region = note.bodyRegion, let info = model.info(for: region) else { continue }
            let k = perRegion[region, default: 0]
            perRegion[region] = k + 1
            let n = info.normal.vector
            let base = info.anchor.vector
            let lift: Float = 0.018 + Float(k) * 0.03
            let node = SCNNode()
            node.name = note.id
            node.position = SCNVector3(base.x + n.x * lift, base.y + n.y * lift + Float(k) * 0.035, base.z + n.z * lift)

            let dot = SCNSphere(radius: 0.017)
            let dm = SCNMaterial()
            dm.lightingModel = .constant
            dm.diffuse.contents = UIColor(hex: 0xFF8A4C)
            dot.materials = [dm]
            let dotNode = SCNNode(geometry: dot)
            dotNode.name = note.id
            node.addChildNode(dotNode)

            let ring = SCNNode(geometry: SCNPlane(width: 0.09, height: 0.09))
            let rm = SCNMaterial()
            rm.lightingModel = .constant
            rm.diffuse.contents = Self.ringImage
            rm.blendMode = .add
            rm.writesToDepthBuffer = false
            ring.geometry?.materials = [rm]
            ring.constraints = [SCNBillboardConstraint()]
            node.addChildNode(ring)
            if !UIAccessibility.isReduceMotionEnabled {
                let pulse = CABasicAnimation(keyPath: "scale")
                pulse.fromValue = NSValue(scnVector3: SCNVector3(0.6, 0.6, 0.6))
                pulse.toValue = NSValue(scnVector3: SCNVector3(1.4, 1.4, 1.4))
                pulse.duration = 1.6
                pulse.repeatCount = .infinity
                let fade = CABasicAnimation(keyPath: "opacity")
                fade.fromValue = 1
                fade.toValue = 0
                fade.duration = 1.6
                fade.repeatCount = .infinity
                ring.addAnimation(pulse, forKey: "pulse")
                ring.addAnimation(fade, forKey: "fade")
            }

            if note.id == focused {
                let label = Self.label(Fmt.shortDate(note.date))
                let h: CGFloat = 0.036
                let plane = SCNPlane(width: h * label.size.width / label.size.height, height: h)
                let lm = SCNMaterial()
                lm.lightingModel = .constant
                lm.diffuse.contents = label
                lm.isDoubleSided = true
                plane.materials = [lm]
                let labelNode = SCNNode(geometry: plane)
                labelNode.position = SCNVector3(0, 0.06, 0)
                labelNode.constraints = [SCNBillboardConstraint()]
                labelNode.renderingOrder = 10
                node.addChildNode(labelNode)
            }
            markers.addChildNode(node)
        }
    }

    static let ringImage: UIImage = UIGraphicsImageRenderer(size: CGSize(width: 64, height: 64)).image { ctx in
        UIColor(hex: 0xFF8A4C).setStroke()
        ctx.cgContext.setLineWidth(4)
        ctx.cgContext.strokeEllipse(in: CGRect(x: 6, y: 6, width: 52, height: 52))
    }

    static func label(_ text: String) -> UIImage {
        let font = UIFont.systemFont(ofSize: 34, weight: .bold)
        let attrs: [NSAttributedString.Key: Any] = [.font: font, .foregroundColor: UIColor.white]
        let size = (text as NSString).size(withAttributes: attrs)
        let pad: CGFloat = 18
        let canvas = CGSize(width: size.width + pad * 2, height: size.height + pad)
        return UIGraphicsImageRenderer(size: canvas).image { _ in
            UIColor(hex: 0xFF8A4C).setFill()
            UIBezierPath(roundedRect: CGRect(origin: .zero, size: canvas), cornerRadius: canvas.height / 2).fill()
            (text as NSString).draw(at: CGPoint(x: pad, y: pad / 2), withAttributes: attrs)
        }
    }

    // MARK: Ambient motion

    private var ambientOn: Bool?

    func setAmbientMotion(_ on: Bool) {
        guard ambientOn != on else { return }
        ambientOn = on
        keyLight.removeAllActions()
        guard on else { return }
        let sway = SCNAction.sequence([
            .rotateTo(x: -0.5, y: 0.6, z: 0, duration: 4.5, usesShortestUnitArc: true),
            .rotateTo(x: -0.5, y: -0.6, z: 0, duration: 4.5, usesShortestUnitArc: true),
        ])
        sway.timingMode = .easeInEaseOut
        keyLight.runAction(.repeatForever(sway))
    }

    // MARK: Input

    func handleTap(at point: CGPoint) {
        guard let view else { return }
        let hits = view.hitTest(point, options: [.searchMode: SCNHitTestSearchMode.all.rawValue, .ignoreHiddenNodes: true])
        for hit in hits {
            var node: SCNNode? = hit.node
            while let n = node, n !== scene.rootNode {
                if n.parent === markers, let id = n.name {
                    onMarker?(id)
                    return
                }
                node = n.parent
            }
        }
        guard let hit = hits.first(where: { $0.node === skinNode || $0.node === muscleNode }) else { return }
        let layerData = hit.node === muscleNode ? model.muscle : model.skin
        guard let picked = model.lookup(layerData, element: hit.geometryIndex, face: hit.faceIndex) else { return }
        onSelect?(picked.0, picked.1)
    }
}

// MARK: - SwiftUI wrapper

struct BodySceneView: UIViewRepresentable {
    let controller: BodySceneController
    var animate: Bool

    func makeUIView(context: Context) -> SCNView {
        let v = SCNView(frame: .zero, options: [SCNView.Option.preferredRenderingAPI.rawValue: SCNRenderingAPI.metal.rawValue])
        v.scene = controller.scene
        v.pointOfView = controller.cameraNode
        v.backgroundColor = .clear
        v.antialiasingMode = .multisampling4X
        v.preferredFramesPerSecond = 60
        v.isPlaying = true
        v.rendersContinuously = animate
        v.accessibilityLabel = "3D body. Drag sideways to turn, pinch to zoom, tap a region."
        controller.view = v

        let pan = UIPanGestureRecognizer(target: context.coordinator, action: #selector(Coordinator.pan(_:)))
        pan.delegate = context.coordinator
        v.addGestureRecognizer(pan)
        v.addGestureRecognizer(UIPinchGestureRecognizer(target: context.coordinator, action: #selector(Coordinator.pinch(_:))))
        v.addGestureRecognizer(UITapGestureRecognizer(target: context.coordinator, action: #selector(Coordinator.tap(_:))))
        return v
    }

    func updateUIView(_ v: SCNView, context: Context) {
        v.rendersContinuously = animate
        controller.setAmbientMotion(animate)
    }

    func makeCoordinator() -> Coordinator { Coordinator(controller: controller) }

    @MainActor
    final class Coordinator: NSObject, UIGestureRecognizerDelegate {
        let controller: BodySceneController
        init(controller: BodySceneController) { self.controller = controller }

        @objc func pan(_ g: UIPanGestureRecognizer) {
            let dx = Float(g.translation(in: g.view).x)
            g.setTranslation(.zero, in: g.view)
            controller.rotate(by: dx * 0.011)
            if g.state == .ended {
                let v = Float(g.velocity(in: g.view).x) * 0.0022
                controller.setYaw(controller.yaw + max(-2.5, min(2.5, v)))
            }
        }

        @objc func pinch(_ g: UIPinchGestureRecognizer) {
            controller.zoom(by: Float(g.scale))
            g.scale = 1
        }

        @objc func tap(_ g: UITapGestureRecognizer) {
            controller.handleTap(at: g.location(in: g.view))
        }

        /// Only horizontal drags turn the figure, so vertical drags keep scrolling the page.
        func gestureRecognizerShouldBegin(_ g: UIGestureRecognizer) -> Bool {
            guard let pan = g as? UIPanGestureRecognizer else { return true }
            let v = pan.velocity(in: pan.view)
            return abs(v.x) > abs(v.y)
        }
    }
}
