import BlithCore
import SceneKit
import SwiftUI
import UIKit

// MARK: - Model

/// The 3D figure, generated by `design/body3d/build_body.py` from BodyParts3D (skin) and Z-Anatomy
/// (muscles), both CC BY-SA; see `design/body3d/LICENSE-ASSETS.md`.
///
/// `body.bin` (format BLB3) holds two layers that share one coordinate space (metres, y up, feet on
/// y = 0, facing +z, the person's left at +x):
/// - `skin`: one geometry element per `BodyRegion`, so tapping returns the region directly and notes
///   stay anchored to regions, never to screen points.
/// - `muscle`: an underlayer (one element per region, no muscle) that keeps the figure continuous,
///   then one element per named muscle. Every triangle also carries its `BodyRegion`.
///
/// Layout (little endian): "BLB3", u32 layerCount, then per layer: u32 vertexCount, triangleCount,
/// groupCount; float3 positions; float3 normals; groups of (u32 region, u32 muscle or 0xFFFFFFFF,
/// u32 firstTriangle, u32 triangleCount); u8 region per triangle, padded to 4 bytes; u32 indices.
final class Body3DModel {
    struct Region: Decodable {
        let id: String
        let anchor: [Float]
        let normal: [Float]
        let radius: Float
    }

    /// A named muscle (or tendon / aponeurosis) instance, e.g. "Gastrocnemius (medial head)", right side.
    struct Muscle: Decodable {
        let id: String
        let name: String
        /// "left", "right" or "midline".
        let side: String
        /// "muscle" or "tendon".
        let kind: String
        /// The `BodyRegion` raw value this muscle mostly lies in.
        let region: String
        let anchor: [Float]
        let normal: [Float]

        var bodyRegion: BodyRegion? { BodyRegion(rawValue: region) }
    }

    struct Meta: Decodable {
        let height: Float
        let regions: [Region]
        let muscles: [Muscle]
        let attribution: String?
        let license: String?
    }

    struct Group {
        /// Index into `meta.regions`.
        let region: Int
        /// Index into `meta.muscles`; nil for skin and underlayer groups.
        let muscle: Int?
        let firstTriangle: Int
        let count: Int
    }

    struct Layer {
        let geometry: SCNGeometry
        let groups: [Group]
        /// Index into `meta.regions` for every triangle of the layer.
        let triangleRegion: [UInt8]
    }

    let meta: Meta
    let skin: Layer
    let muscle: Layer

    static let shared: Body3DModel? = Body3DModel()

    private init?() {
        guard let binURL = Bundle.main.url(forResource: "body", withExtension: "bin"),
              let jsonURL = Bundle.main.url(forResource: "body3d", withExtension: "json"),
              let data = try? Data(contentsOf: binURL, options: .mappedIfSafe),
              let json = try? Data(contentsOf: jsonURL),
              let meta = try? JSONDecoder().decode(Meta.self, from: json),
              data.count > 8, String(data: data.prefix(4), encoding: .ascii) == "BLB3" else { return nil }
        var offset = 8
        guard Self.u32(data, 4) >= 2,
              let skin = Self.readLayer(data, &offset),
              let muscle = Self.readLayer(data, &offset) else { return nil }
        self.meta = meta
        self.skin = skin
        self.muscle = muscle
    }

    private static func u32(_ data: Data, _ offset: Int) -> Int {
        Int(data.subdata(in: offset..<offset + 4).withUnsafeBytes { $0.loadUnaligned(as: UInt32.self) }.littleEndian)
    }

    private static func readLayer(_ data: Data, _ offset: inout Int) -> Layer? {
        guard data.count >= offset + 12 else { return nil }
        let v = u32(data, offset), t = u32(data, offset + 4), g = u32(data, offset + 8)
        var o = offset + 12
        let posOffset = o; o += v * 12
        let nrmOffset = o; o += v * 12
        guard data.count >= o + g * 16 else { return nil }
        var groups: [Group] = []
        for i in 0..<g {
            let b = o + i * 16
            let m = u32(data, b + 4)
            groups.append(Group(region: u32(data, b), muscle: m == 0xFFFF_FFFF ? nil : m,
                                firstTriangle: u32(data, b + 8), count: u32(data, b + 12)))
        }
        o += g * 16
        guard data.count >= o + t else { return nil }
        let triangleRegion = [UInt8](data.subdata(in: o..<o + t))
        o += t + (4 - t % 4) % 4
        let indexOffset = o
        o += t * 12
        guard data.count >= o else { return nil }

        let positions = SCNGeometrySource(data: data.subdata(in: posOffset..<posOffset + v * 12), semantic: .vertex, vectorCount: v,
                                          usesFloatComponents: true, componentsPerVector: 3, bytesPerComponent: 4, dataOffset: 0, dataStride: 12)
        let normals = SCNGeometrySource(data: data.subdata(in: nrmOffset..<nrmOffset + v * 12), semantic: .normal, vectorCount: v,
                                        usesFloatComponents: true, componentsPerVector: 3, bytesPerComponent: 4, dataOffset: 0, dataStride: 12)
        let elements = groups.map { grp in
            let start = indexOffset + grp.firstTriangle * 12
            return SCNGeometryElement(data: data.subdata(in: start..<start + grp.count * 12), primitiveType: .triangles,
                                      primitiveCount: grp.count, bytesPerIndex: 4)
        }
        offset = o
        return Layer(geometry: SCNGeometry(sources: [positions, normals], elements: elements), groups: groups,
                     triangleRegion: triangleRegion)
    }

    func regionIndex(_ region: BodyRegion) -> Int? { meta.regions.firstIndex { $0.id == region.rawValue } }

    func muscleIndex(_ muscle: Muscle) -> Int? { meta.muscles.firstIndex { $0.id == muscle.id } }

    /// Region and muscle under a hit on `layer`: element index and face index within that element.
    func lookup(_ layer: Layer, element: Int, face: Int) -> (BodyRegion, Muscle?)? {
        guard layer.groups.indices.contains(element) else { return nil }
        let group = layer.groups[element]
        let tri = group.firstTriangle + face
        let r = layer.triangleRegion.indices.contains(tri) ? Int(layer.triangleRegion[tri]) : group.region
        guard meta.regions.indices.contains(r), let region = BodyRegion(rawValue: meta.regions[r].id) else { return nil }
        let muscle = group.muscle.flatMap { meta.muscles.indices.contains($0) ? meta.muscles[$0] : nil }
        return (region, muscle)
    }

    func info(for region: BodyRegion) -> Region? { meta.regions.first { $0.id == region.rawValue } }
}

extension Array where Element == Float {
    var vector: SCNVector3 { count >= 3 ? SCNVector3(self[0], self[1], self[2]) : SCNVector3Zero }
}

// MARK: - Scene

enum BodyLayer: String, CaseIterable, Identifiable {
    case skin, muscle
    var id: String { rawValue }
    var title: String { self == .skin ? "Figure" : "Muscles" }
}

/// How much anatomy the muscle layer shows. Soft radiant is the default; Minimal glow flattens the
/// tone between muscles for people who want less detail.
enum AnatomyStyle: String, CaseIterable, Identifiable {
    case radiant, minimal
    var id: String { rawValue }
    var title: String { self == .radiant ? "Soft radiant" : "Minimal glow" }
    /// The shader's `detail` value: 1 keeps muscle borders and tone variation, 0 flattens them.
    var detail: Float { self == .radiant ? 1 : 0 }
    var occlusion: CGFloat { self == .radiant ? 0.6 : 0.3 }
    /// How much of the skin shell covers the muscles: Soft radiant lets the anatomy show through,
    /// Minimal glow keeps the body smoother.
    var shellOpacity: CGFloat { self == .radiant ? 0.34 : 0.62 }
}

/// The dark imaging chamber the figure stands in (the documented hex exception, like the lighting).
enum BodyChamber {
    static let centre = Color(hex: 0x0C1C2B)
    static let middle = Color(hex: 0x091827)
    static let edge = Color(hex: 0x07111C)
}

/// Owns the SceneKit scene and all camera moves. Rotation is a turntable around the body's
/// vertical axis; zoom moves the camera toward a target point on the body.
@MainActor
final class BodySceneController: NSObject {
    let scene = SCNScene()
    let model: Body3DModel
    let turntable = SCNNode()
    /// Glass figure (skin layer).
    let skinNode: SCNNode
    /// Anatomical muscles (muscle layer). Only the node of the current layer is visible.
    let muscleNode: SCNNode
    /// The skin's smooth head, shown on the muscle layer instead of exposed facial muscles.
    let headNode: SCNNode
    /// The rest of the skin as a translucent shell over the muscles (muscle layer only). It is not
    /// hit-tested, so taps reach the muscles underneath.
    let shellNode: SCNNode
    /// Opaque inside of the body behind everything on the muscle layer (see `backingGeometry`).
    let backingNode: SCNNode
    /// Region index (into `meta.regions`) of each shell element.
    private let shellRegions: [Int]
    private var shellMaterials: [SCNMaterial] = []
    private var floorMaterial: SCNMaterial?
    let cameraNode = SCNNode()
    let rig = SCNNode()
    let keyLight = SCNNode()
    let markers = SCNNode()
    weak var view: SCNView?

    var layer: BodyLayer = .skin
    private(set) var yaw: Float = 0
    private(set) var distance: Float = 3.9
    private var target = SCNVector3(0, 0.93, 0)
    private var skinMaterials: [SCNMaterial] = []
    private var muscleMaterials: [SCNMaterial] = []
    private var headMaterial = SCNMaterial()
    /// Muscle-layer elements that are never drawn (the facial muscles under the smooth head).
    private var hiddenGroups = Set<Int>()
    private var muscleState: [MaterialState] = []
    private var headState = MaterialState()
    private(set) var style: AnatomyStyle = .radiant
    private let ambientLight = SCNLight()
    private let rimLight = SCNLight()
    var onSelect: ((BodyRegion, Body3DModel.Muscle?) -> Void)?
    var onMarker: ((String) -> Void)?
    /// Any drag, pinch or tap on the figure (used to retire the first-visit hints).
    var onInteract: (() -> Void)?

    /// Shader state of one muscle-layer element; see `anatomyShader`.
    struct MaterialState: Equatable {
        var highlight: Float = 0
        var press: Float = 0
        var dim: Float = 0
    }

    static let fullDistance: Float = 3.9
    static let fullTarget = SCNVector3(0, 0.93, 0)

    init(model: Body3DModel) {
        self.model = model
        skinNode = SCNNode(geometry: model.skin.geometry.copy() as? SCNGeometry)
        muscleNode = SCNNode(geometry: model.muscle.geometry.copy() as? SCNGeometry)
        headNode = SCNNode(geometry: BodySceneController.headGeometry(model))
        let shell = BodySceneController.shellGeometry(model)
        shellNode = SCNNode(geometry: shell.geometry)
        shellRegions = shell.regions
        backingNode = SCNNode(geometry: BodySceneController.backingGeometry(model))
        super.init()
        build()
    }

    private func build() {
        scene.background.contents = UIColor.clear
        skinMaterials = model.skin.groups.map { _ in Self.skinMaterial() }
        let head = headNode.geometry == nil ? nil : model.regionIndex(.head)
        muscleMaterials = model.muscle.groups.enumerated().map { i, group in
            if let head, group.region == head {
                hiddenGroups.insert(i)
                return Self.hiddenMaterial()
            }
            guard let m = group.muscle, model.meta.muscles.indices.contains(m) else {
                return Self.anatomyMaterial(base: Self.underlayer, vary: 0)
            }
            let muscle = model.meta.muscles[m]
            return Self.anatomyMaterial(base: muscle.kind == "tendon" ? Self.tendon : Self.ivory, vary: Self.variation(for: muscle))
        }
        muscleState = Array(repeating: MaterialState(), count: muscleMaterials.count)
        headMaterial = Self.anatomyMaterial(base: Self.ivory, vary: 0)
        shellMaterials = shellRegions.map { _ in Self.shellMaterial(opacity: style.shellOpacity) }
        shellNode.geometry?.materials = shellMaterials
        backingNode.geometry?.materials = [Self.backingMaterial()]
        skinNode.geometry?.materials = skinMaterials
        muscleNode.geometry?.materials = muscleMaterials
        headNode.geometry?.materials = [headMaterial]
        turntable.addChildNode(skinNode)
        turntable.addChildNode(muscleNode)
        turntable.addChildNode(headNode)
        turntable.addChildNode(shellNode)
        turntable.addChildNode(backingNode)
        turntable.addChildNode(markers)
        scene.rootNode.addChildNode(turntable)
        scene.rootNode.addChildNode(floorNode())

        let camera = SCNCamera()
        camera.fieldOfView = 30
        camera.zNear = 0.05
        camera.zFar = 30
        camera.wantsHDR = true
        camera.bloomIntensity = 0.55
        camera.bloomThreshold = 0.6
        camera.bloomBlurRadius = 10
        camera.screenSpaceAmbientOcclusionRadius = 0.035
        cameraNode.camera = camera
        rig.addChildNode(cameraNode)
        scene.rootNode.addChildNode(rig)

        let ambient = SCNNode()
        ambientLight.type = .ambient
        ambient.light = ambientLight
        scene.rootNode.addChildNode(ambient)

        keyLight.light = SCNLight()
        keyLight.light?.type = .directional
        keyLight.light?.intensity = 900
        keyLight.light?.color = UIColor(hex: 0xDCE6FF)
        keyLight.eulerAngles = SCNVector3(-0.5, -0.6, 0)
        scene.rootNode.addChildNode(keyLight)

        let rim = SCNNode()
        rimLight.type = .directional
        rim.light = rimLight
        rim.eulerAngles = SCNVector3(-0.2, .pi * 0.85, 0)
        scene.rootNode.addChildNode(rim)
        setLayer(.skin)
        applyCamera(animated: false)
    }

    static let fresnel = """
    float3 n = normalize(_surface.normal);
    float3 v = normalize(-_surface.position);
    float f = pow(1.0 - saturate(dot(n, v)), 2.2);
    """

    /// Luminous cobalt glass: deep #1B3A8C in shadow, #4F8EFF where lit, an ice (#B9DAFF) Fresnel
    /// rim, slightly translucent (front-most layer only, so the figure never shows its own inside).
    static func skinMaterial() -> SCNMaterial {
        let m = SCNMaterial()
        m.lightingModel = .lambert
        m.diffuse.contents = UIColor(hex: 0x4F8EFF)
        m.emission.contents = UIColor(hex: 0x10265E)
        m.transparency = 0.9
        m.transparencyMode = .singleLayer
        m.setValue(Float(0), forKey: "highlight")
        m.shaderModifiers = [
            .fragment: """
            #pragma arguments
            float highlight;
            #pragma body
            \(fresnel)
            _output.color.rgb += float3(0.725, 0.855, 1.0) * f * 1.15;
            _output.color.rgb += float3(0.49, 0.70, 1.0) * highlight * (0.08 + 0.32 * f);
            """,
        ]
        return m
    }

    // MARK: Soft radiant anatomy

    /// Warm ivory resin rather than exposed tissue; tendons a touch paler, the underlayer (seen only
    /// in the gaps between muscles) a touch deeper.
    static let ivory = UIColor(hex: 0xD99A7E)
    static let tendon = UIColor(hex: 0xDDAA92)
    static let underlayer = UIColor(hex: 0xA86A55)
    /// The translucent skin (it also covers the opaque head, which sits just inside it).
    static let skinTone = UIColor(hex: 0xF1C7AF)

    /// A stable value in -1...1 per muscle name, so neighbouring muscles differ by a few percent of tone.
    static func variation(for muscle: Body3DModel.Muscle) -> Float {
        var h: UInt32 = 2_166_136_261
        for b in muscle.name.utf8 { h = (h ^ UInt32(b)) &* 16_777_619 }
        return Float(h % 2001) / 1000 - 1
    }

    /// Every muscle shares this shader (compiled once); its state is a handful of uniforms:
    /// `highlight` selected (soft blue core, lavender toward the edge, a faint cyan light inside),
    /// `press` touched or in the chosen region (pale blue edge only), `dim` something else is
    /// selected, `detail` 1 for Soft radiant and 0 for Minimal glow, `vary` the per-muscle tone.
    /// Lit colour is pulled toward the base colour so the figure reads as frosted resin, with a cool
    /// rim and a little warmth where the surface turns away, like light passing through.
    static let anatomyShader = """
    #pragma arguments
    float highlight;
    float press;
    float dim;
    float detail;
    float vary;
    #pragma body
    float3 srN = normalize(_surface.normal);
    float3 srV = normalize(-_surface.position);
    float srNdv = saturate(dot(srN, srV));
    float srF = pow(1.0 - srNdv, 2.4);
    float3 srCol = mix(_output.color.rgb, _surface.diffuse.rgb * (0.78 + 0.22 * srNdv), (0.30 - 0.15 * detail));
    srCol *= 1.0 + vary * (0.012 + 0.038 * detail);
    srCol += float3(0.30, 0.16, 0.10) * pow(1.0 - srNdv, 1.5) * 0.12;
    srCol += float3(0.62, 0.76, 1.0) * srF * (0.05 + 0.04 * detail);
    float srLit = saturate(highlight + press);
    float srLum = dot(srCol, float3(0.2126, 0.7152, 0.0722));
    srCol = mix(srCol, mix(float3(srLum), srCol, 0.7) * 0.7, dim * (1.0 - srLit));
    float3 srTint = mix(float3(0.10, 0.26, 1.0), float3(0.33, 0.26, 1.0), srF);
    srCol = mix(srCol, srTint * (0.42 + 0.40 * srNdv), saturate(highlight) * 0.8);
    srCol += float3(0.08, 0.48, 1.0) * pow(srNdv, 3.0) * 0.20 * highlight;
    srCol += float3(0.52, 0.72, 1.0) * srF * (0.60 * highlight + 0.55 * press);
    _output.color.rgb = srCol;
    """

    static func anatomyMaterial(base: UIColor, vary: Float) -> SCNMaterial {
        let m = SCNMaterial()
        m.lightingModel = .blinn
        m.diffuse.contents = base
        m.specular.contents = UIColor(white: 0.14, alpha: 1)
        m.shininess = 0.22
        m.setValue(Float(0), forKey: "highlight")
        m.setValue(Float(0), forKey: "press")
        m.setValue(Float(0), forKey: "dim")
        m.setValue(Float(1), forKey: "detail")
        m.setValue(vary, forKey: "vary")
        m.shaderModifiers = [.fragment: anatomyShader]
        return m
    }

    /// Draws nothing; keeps an element (and every index after it) without showing it.
    static func hiddenMaterial() -> SCNMaterial {
        let m = SCNMaterial()
        m.lightingModel = .constant
        m.colorBufferWriteMask = []
        m.writesToDepthBuffer = false
        return m
    }

    /// The skin layer's head elements on their own: a smooth, mannequin-like head for the muscle layer.
    static func headGeometry(_ model: Body3DModel) -> SCNGeometry? {
        guard let head = model.regionIndex(.head) else { return nil }
        let source = model.skin.geometry
        let elements = model.skin.groups.indices
            .filter { model.skin.groups[$0].region == head && $0 < source.elements.count }
            .map { source.elements[$0] }
        guard !elements.isEmpty else { return nil }
        return SCNGeometry(sources: inflatedSources(source, offsets: skinOffsets(model).map { $0 - 0.005 }), elements: elements)
    }

    /// How far the skin is pushed out along its normals on the muscle layer: some muscles sit a little
    /// outside the scanned skin (99.9% within 1.6 cm), and would otherwise poke through the shell in
    /// patches. The head (no muscles drawn under it), hands and feet stay close so the face and
    /// fingers keep their shape; the offset is blended across a few rings of vertices so no ridge forms.
    static let skinOffset: Float = 0.016
    static let closeOffsets: [BodyRegion: Float] = [.head: 0.002, .rightHand: 0.003, .leftHand: 0.003,
                                                     .rightFoot: 0.004, .leftFoot: 0.004]

    /// Per-vertex offset for the skin layer, computed once and shared by the shell and the head.
    static let offsetCache = OffsetCache()
    final class OffsetCache { var value: [Float]? }

    static func skinOffsets(_ model: Body3DModel) -> [Float] {
        if let cached = offsetCache.value { return cached }
        let geometry = model.skin.geometry
        let count = geometry.sources(for: .vertex).first?.vectorCount ?? 0
        // Measured per vertex by design/body3d/skin_offsets.py: just enough to clear the muscles there.
        if let measured = measuredOffsets(count: count) {
            offsetCache.value = measured
            return measured
        }
        var out = [Float](repeating: skinOffset, count: count)
        var triangles: [Int] = []
        for (i, group) in model.skin.groups.enumerated() where i < geometry.elements.count {
            let element = geometry.elements[i]
            guard element.bytesPerIndex == 4 else { continue }
            var indices: [Int] = []
            element.data.withUnsafeBytes { raw in
                for k in 0..<min(element.primitiveCount * 3, raw.count / 4) {
                    let v = Int(raw.loadUnaligned(fromByteOffset: k * 4, as: UInt32.self))
                    if v < count { indices.append(v) }
                }
            }
            if indices.count % 3 == 0 { triangles += indices }
            guard model.meta.regions.indices.contains(group.region),
                  let region = BodyRegion(rawValue: model.meta.regions[group.region].id),
                  let close = closeOffsets[region] else { continue }
            for v in indices { out[v] = min(out[v], close) }
        }
        for _ in 0..<8 {
            var sum = [Float](repeating: 0, count: count)
            var weight = [Float](repeating: 0, count: count)
            for t in stride(from: 0, to: triangles.count - 2, by: 3) {
                let a = triangles[t], b = triangles[t + 1], c = triangles[t + 2]
                let total = out[a] + out[b] + out[c]
                sum[a] += total; sum[b] += total; sum[c] += total
                weight[a] += 3; weight[b] += 3; weight[c] += 3
            }
            for v in 0..<count where weight[v] > 0 { out[v] = sum[v] / weight[v] }
        }
        offsetCache.value = out
        return out
    }

    /// `skin_offsets.bin` ("BLO1", u32 count, float32 per skin vertex), if present and matching the model.
    static func measuredOffsets(count: Int) -> [Float]? {
        guard let url = Bundle.main.url(forResource: "skin_offsets", withExtension: "bin"),
              let data = try? Data(contentsOf: url), data.count == 8 + count * 4,
              String(data: data.prefix(4), encoding: .ascii) == "BLO1" else { return nil }
        return data.withUnsafeBytes { raw in
            (0..<count).map { raw.loadUnaligned(fromByteOffset: 8 + $0 * 4, as: Float.self) }
        }
    }

    /// The inside of the body seen from within (back faces only, drawn opaque in a deep skin tone).
    /// It sits behind the muscles from any angle and fills the gap between muscles and skin, so the
    /// translucent skin never shows the background through it as a pale outline.
    static func backingGeometry(_ model: Body3DModel) -> SCNGeometry? {
        let source = model.skin.geometry
        guard !source.elements.isEmpty else { return nil }
        return SCNGeometry(sources: inflatedSources(source, offsets: skinOffsets(model).map { $0 - 0.002 }),
                           elements: source.elements)
    }

    static func backingMaterial() -> SCNMaterial {
        let m = SCNMaterial()
        m.lightingModel = .constant
        m.diffuse.contents = UIColor(hex: 0xD0907A)
        m.cullMode = .front
        return m
    }

    /// The geometry's sources with every vertex moved along its normal by its offset (computed once).
    static func inflatedSources(_ geometry: SCNGeometry, offsets: [Float]) -> [SCNGeometrySource] {
        guard let pos = geometry.sources(for: .vertex).first, let nrm = geometry.sources(for: .normal).first,
              pos.vectorCount == nrm.vectorCount, pos.usesFloatComponents, nrm.usesFloatComponents,
              pos.bytesPerComponent == 4, nrm.bytesPerComponent == 4,
              pos.componentsPerVector == 3, nrm.componentsPerVector == 3 else { return geometry.sources }
        let n = pos.vectorCount
        var out = [Float](repeating: 0, count: n * 3)
        pos.data.withUnsafeBytes { p in
            nrm.data.withUnsafeBytes { q in
                for i in 0..<n {
                    for k in 0..<3 {
                        let a = p.loadUnaligned(fromByteOffset: pos.dataOffset + i * pos.dataStride + k * 4, as: Float.self)
                        let b = q.loadUnaligned(fromByteOffset: nrm.dataOffset + i * nrm.dataStride + k * 4, as: Float.self)
                        out[i * 3 + k] = a + b * (i < offsets.count ? offsets[i] : skinOffset)
                    }
                }
            }
        }
        let data = out.withUnsafeBufferPointer { Data(buffer: $0) }
        let inflated = SCNGeometrySource(data: data, semantic: .vertex, vectorCount: n, usesFloatComponents: true,
                                         componentsPerVector: 3, bytesPerComponent: 4, dataOffset: 0, dataStride: 12)
        return [inflated, nrm]
    }

    /// The whole skin as the shell (over the opaque head too), and each element's region.
    static func shellGeometry(_ model: Body3DModel) -> (geometry: SCNGeometry?, regions: [Int]) {
        let source = model.skin.geometry
        let indices = model.skin.groups.indices.filter { $0 < source.elements.count }
        guard !indices.isEmpty else { return (nil, []) }
        return (SCNGeometry(sources: inflatedSources(source, offsets: skinOffsets(model)), elements: indices.map { source.elements[$0] }),
                indices.map { model.skin.groups[$0].region })
    }

    /// Smooth translucent skin over the muscles: lit peach with a soft sheen and a warm bright edge,
    /// the front-most layer only. `dim` darkens it when a muscle elsewhere is selected; `highlight`
    /// tints it faintly blue over a chosen region.
    static let shellShader = """
    #pragma arguments
    float dim;
    float highlight;
    #pragma body
    float3 shN = normalize(_surface.normal);
    float3 shV = normalize(-_surface.position);
    float shF = pow(1.0 - saturate(dot(shN, shV)), 3.0);
    float3 shCol = _output.color.rgb + float3(1.0, 0.76, 0.62) * shF * 0.16;
    shCol = mix(shCol, shCol * 0.72, dim);
    shCol += float3(0.10, 0.26, 1.0) * highlight * (0.10 + 0.25 * shF);
    _output.color.rgb = shCol;
    """

    static func shellMaterial(opacity: CGFloat) -> SCNMaterial {
        let m = SCNMaterial()
        m.lightingModel = .blinn
        m.diffuse.contents = skinTone
        m.specular.contents = UIColor(white: 0.25, alpha: 1)
        m.shininess = 0.4
        m.transparency = opacity
        m.transparencyMode = .singleLayer
        m.setValue(Float(0), forKey: "dim")
        m.setValue(Float(0), forKey: "highlight")
        m.shaderModifiers = [.fragment: shellShader]
        return m
    }

    static let floorBlue = floorImage(glow: UIColor(hex: 0x4C8DFF), ring: UIColor(hex: 0x3DDCFF))
    static let floorWarm = floorImage(glow: UIColor(hex: 0xFFE3D4), ring: UIColor(hex: 0xFFF1E8))

    static func floorImage(glow: UIColor, ring: UIColor) -> UIImage {
        let size = 256
        return UIGraphicsImageRenderer(size: CGSize(width: size, height: size)).image { ctx in
            let colors = [glow.withAlphaComponent(0.45).cgColor, glow.withAlphaComponent(0.1).cgColor, UIColor.clear.cgColor] as CFArray
            let g = CGGradient(colorsSpace: CGColorSpaceCreateDeviceRGB(), colors: colors, locations: [0, 0.45, 1])!
            let c = CGPoint(x: size / 2, y: size / 2)
            ctx.cgContext.drawRadialGradient(g, startCenter: c, startRadius: 0, endCenter: c, endRadius: CGFloat(size) / 2, options: [])
            ring.withAlphaComponent(0.5).setStroke()
            for r in [0.3, 0.42] {
                let rr = CGFloat(size) * r
                ctx.cgContext.setLineWidth(1.5)
                ctx.cgContext.strokeEllipse(in: CGRect(x: c.x - rr, y: c.y - rr, width: rr * 2, height: rr * 2))
            }
        }
    }

    func floorNode() -> SCNNode {
        let plane = SCNPlane(width: 1.5, height: 1.5)
        let m = SCNMaterial()
        m.lightingModel = .constant
        m.diffuse.contents = Self.floorBlue
        floorMaterial = m
        m.isDoubleSided = true
        m.writesToDepthBuffer = false
        m.blendMode = .add
        plane.materials = [m]
        let node = SCNNode(geometry: plane)
        node.eulerAngles.x = -.pi / 2
        node.position.y = 0.002
        return node
    }

    // MARK: Layer and highlight

    func setLayer(_ layer: BodyLayer) {
        self.layer = layer
        skinNode.isHidden = layer != .skin
        muscleNode.isHidden = layer != .muscle
        headNode.isHidden = layer != .muscle
        shellNode.isHidden = layer != .muscle
        backingNode.isHidden = layer != .muscle
        floorMaterial?.diffuse.contents = layer == .muscle ? Self.floorWarm : Self.floorBlue
        let camera = cameraNode.camera
        if layer == .skin {
            keyLight.light?.intensity = 900
            keyLight.light?.color = UIColor(hex: 0xDCE6FF)
            ambientLight.intensity = 260
            ambientLight.color = UIColor(hex: 0x9FB4FF)
            rimLight.intensity = 500
            rimLight.color = UIColor(hex: 0x3DDCFF)
            camera?.screenSpaceAmbientOcclusionIntensity = 0
            camera?.bloomIntensity = 0.55
            camera?.bloomThreshold = 0.6
            camera?.wantsExposureAdaptation = true
            camera?.exposureOffset = 0
        } else {
            // Warm studio light for a smooth body with the anatomy beneath. Bloom is nearly off: only
            // the bright skin edge and the selected muscle catch a little of it.
            keyLight.light?.intensity = 1000
            keyLight.light?.color = UIColor(hex: 0xFFF0E6)
            ambientLight.intensity = 260
            ambientLight.color = UIColor(hex: 0xFFE9DE)
            rimLight.intensity = 600
            rimLight.color = UIColor(hex: 0xCFE0FF)
            camera?.screenSpaceAmbientOcclusionIntensity = style.occlusion
            camera?.bloomIntensity = 0
            camera?.bloomThreshold = 1
            // Fixed exposure: auto exposure brightens for the dark chamber and blows the peach skin
            // out to cream, with thin tendons clipping to white.
            camera?.wantsExposureAdaptation = false
            camera?.exposureOffset = 0.2
        }
    }

    func setStyle(_ style: AnatomyStyle) {
        self.style = style
        for m in muscleMaterials + [headMaterial] { m.setValue(style.detail, forKey: "detail") }
        if layer == .muscle { cameraNode.camera?.screenSpaceAmbientOcclusionIntensity = style.occlusion }
        applyShell(animated: false)
    }

    /// Region whose skin clears so the selection underneath shows; nil when nothing is selected.
    private var clearedRegion: Int?
    private var shellDimmed = false

    /// Skin shell opacity and tint for the current selection: the chosen region's skin thins so the
    /// muscle's light shows through, the rest of the skin dims with the muscles.
    private func applyShell(animated: Bool) {
        let reduce = UIAccessibility.isReduceMotionEnabled
        SCNTransaction.begin()
        SCNTransaction.animationDuration = animated && !reduce ? 0.3 : 0
        for (i, m) in shellMaterials.enumerated() {
            let cleared = clearedRegion == shellRegions[i]
            m.transparency = cleared ? 0.12 : style.shellOpacity
            m.setValue(shellDimmed && !cleared ? Float(1) : Float(0), forKey: "dim")
            m.setValue(cleared ? Float(1) : Float(0), forKey: "highlight")
        }
        SCNTransaction.commit()
    }

    /// Selection states. Figure layer: the region glows. Muscle layer: a chosen muscle turns radiant
    /// blue and everything else dims a little; a region without a muscle lights the edges of its
    /// muscles (the touch state). Nothing selected is the calm resting state.
    func highlight(_ region: BodyRegion?, muscle: Body3DModel.Muscle? = nil) {
        let r = region.flatMap(model.regionIndex)
        for (i, g) in model.skin.groups.enumerated() {
            skinMaterials[i].setValue(r != nil && g.region == r ? Float(1) : Float(0), forKey: "highlight")
        }
        let mi = muscle.flatMap(model.muscleIndex)
        let headOnly = mi == nil && region == .head && headNode.geometry != nil
        let active = r != nil || mi != nil
        for (i, g) in model.muscle.groups.enumerated() where !hiddenGroups.contains(i) {
            var next = MaterialState()
            if let mi {
                next.highlight = g.muscle == mi ? 1 : 0
            } else if let r, !headOnly {
                next.press = g.region == r ? 1 : 0
            }
            next.dim = active && next.highlight + next.press == 0 ? 1 : 0
            Self.transition(muscleMaterials[i], from: muscleState[i], to: next)
            muscleState[i] = next
        }
        var head = MaterialState()
        head.highlight = headOnly ? 1 : 0
        head.dim = active && !headOnly ? 1 : 0
        Self.transition(headMaterial, from: headState, to: head)
        headState = head
        clearedRegion = muscle?.bodyRegion.flatMap(model.regionIndex) ?? (headOnly ? nil : r)
        shellDimmed = active
        applyShell(animated: true)
    }

    static func transition(_ m: SCNMaterial, from old: MaterialState, to new: MaterialState) {
        guard old != new else { return }
        animate(m, "highlight", from: old.highlight, to: new.highlight, swell: new.highlight > old.highlight)
        animate(m, "press", from: old.press, to: new.press)
        animate(m, "dim", from: old.dim, to: new.dim)
    }

    /// Eases a shader uniform to its new value over about 300 ms. A newly selected muscle swells once
    /// and settles, then holds steady (no repeating glow). Reduce Motion sets values directly.
    static func animate(_ m: SCNMaterial, _ key: String, from old: Float, to value: Float, swell: Bool = false) {
        guard old != value else { return }
        m.setValue(value, forKey: key)
        guard !UIAccessibility.isReduceMotionEnabled else { return }
        let animation: CAAnimation
        if swell {
            let k = CAKeyframeAnimation(keyPath: key)
            k.values = [old, value * 1.2, value]
            k.keyTimes = [0, 0.5, 1]
            k.timingFunctions = [CAMediaTimingFunction(name: .easeOut), CAMediaTimingFunction(name: .easeInEaseOut)]
            k.duration = 0.36
            animation = k
        } else {
            let b = CABasicAnimation(keyPath: key)
            b.fromValue = old
            b.toValue = value
            b.duration = 0.28
            b.timingFunction = CAMediaTimingFunction(name: .easeInEaseOut)
            animation = b
        }
        m.addAnimation(animation, forKey: key)
    }

    // MARK: Camera

    func applyCamera(animated: Bool, duration: Double = 0.8) {
        SCNTransaction.begin()
        SCNTransaction.animationDuration = animated ? duration : 0
        SCNTransaction.animationTimingFunction = CAMediaTimingFunction(controlPoints: 0.23, 1, 0.32, 1)
        turntable.eulerAngles.y = yaw
        rig.position = target
        cameraNode.position = SCNVector3(0, 0.05 * distance / Self.fullDistance, distance)
        cameraNode.eulerAngles = SCNVector3(-0.012, 0, 0)
        SCNTransaction.commit()
    }

    func rotate(by delta: Float) {
        yaw += delta
        turntable.eulerAngles.y = yaw
    }

    /// Front, side and back are slightly magnetic: a turn that ends within about 11° of one settles there.
    static func snapped(_ yaw: Float) -> Float {
        let quarter = Float.pi / 2
        let nearest = (yaw / quarter).rounded() * quarter
        return abs(yaw - nearest) < 0.2 ? nearest : yaw
    }

    func setYaw(_ value: Float, animated: Bool = true) {
        var d = (value - yaw).truncatingRemainder(dividingBy: 2 * .pi)
        if d > .pi { d -= 2 * .pi }
        if d < -.pi { d += 2 * .pi }
        yaw += d
        applyCamera(animated: animated)
    }

    func zoom(by factor: Float, animated: Bool = false) {
        distance = max(0.7, min(Self.fullDistance, distance / factor))
        if distance > Self.fullDistance * 0.92 { target = Self.fullTarget }
        applyCamera(animated: animated, duration: 0.35)
    }

    func reset(animated: Bool = true) {
        distance = Self.fullDistance
        target = Self.fullTarget
        highlight(nil)
        applyCamera(animated: animated)
    }

    /// Turn the region toward the viewer and frame it.
    func focus(_ region: BodyRegion, animated: Bool = true) {
        guard let info = model.info(for: region) else { return }
        let n = info.normal.vector
        let facing = abs(n.x) + abs(n.z) > 0.2 ? -atan2(n.x, n.z) : yaw
        var d = (facing - yaw).truncatingRemainder(dividingBy: 2 * .pi)
        if d > .pi { d -= 2 * .pi }
        if d < -.pi { d += 2 * .pi }
        yaw += d
        let a = info.anchor.vector
        let c = cos(yaw), s = sin(yaw)
        target = SCNVector3(a.x * c + a.z * s, a.y, -a.x * s + a.z * c)
        distance = max(1.35, min(2.6, info.radius * 9))
        highlight(region)
        applyCamera(animated: animated, duration: 0.9)
    }

    /// Where a region's anchor appears in the view, for overlays such as the first-visit hints.
    func screenPoint(of region: BodyRegion) -> CGPoint? {
        guard let view, view.bounds.width > 0, let info = model.info(for: region) else { return nil }
        let p = view.projectPoint(turntable.convertPosition(info.anchor.vector, to: nil))
        return CGPoint(x: CGFloat(p.x), y: CGFloat(p.y))
    }

    // MARK: Markers

    func setMarkers(_ notes: [HealthEvent], focused: String?, today: LocalDate) {
        markers.childNodes.forEach { $0.removeFromParentNode() }
        var perRegion: [BodyRegion: Int] = [:]
        for note in notes {
            guard let region = note.bodyRegion, let info = model.info(for: region) else { continue }
            let k = perRegion[region, default: 0]
            perRegion[region] = k + 1
            let n = info.normal.vector
            let base = info.anchor.vector
            let lift: Float = 0.018 + Float(k) * 0.03
            let node = SCNNode()
            node.name = note.id
            node.position = SCNVector3(base.x + n.x * lift, base.y + n.y * lift + Float(k) * 0.035, base.z + n.z * lift)

            let dot = SCNSphere(radius: 0.017)
            let dm = SCNMaterial()
            dm.lightingModel = .constant
            dm.diffuse.contents = UIColor(hex: 0xFF8A4C)
            dot.materials = [dm]
            let dotNode = SCNNode(geometry: dot)
            dotNode.name = note.id
            node.addChildNode(dotNode)

            let ring = SCNNode(geometry: SCNPlane(width: 0.09, height: 0.09))
            let rm = SCNMaterial()
            rm.lightingModel = .constant
            rm.diffuse.contents = Self.ringImage
            rm.blendMode = .add
            rm.writesToDepthBuffer = false
            ring.geometry?.materials = [rm]
            ring.constraints = [SCNBillboardConstraint()]
            node.addChildNode(ring)
            if !UIAccessibility.isReduceMotionEnabled {
                let pulse = CABasicAnimation(keyPath: "scale")
                pulse.fromValue = NSValue(scnVector3: SCNVector3(0.6, 0.6, 0.6))
                pulse.toValue = NSValue(scnVector3: SCNVector3(1.4, 1.4, 1.4))
                pulse.duration = 1.6
                pulse.repeatCount = .infinity
                let fade = CABasicAnimation(keyPath: "opacity")
                fade.fromValue = 1
                fade.toValue = 0
                fade.duration = 1.6
                fade.repeatCount = .infinity
                ring.addAnimation(pulse, forKey: "pulse")
                ring.addAnimation(fade, forKey: "fade")
            }

            if note.id == focused {
                let label = Self.label(Fmt.shortDate(note.date))
                let h: CGFloat = 0.036
                let plane = SCNPlane(width: h * label.size.width / label.size.height, height: h)
                let lm = SCNMaterial()
                lm.lightingModel = .constant
                lm.diffuse.contents = label
                lm.isDoubleSided = true
                plane.materials = [lm]
                let labelNode = SCNNode(geometry: plane)
                labelNode.position = SCNVector3(0, 0.06, 0)
                labelNode.constraints = [SCNBillboardConstraint()]
                labelNode.renderingOrder = 10
                node.addChildNode(labelNode)
            }
            markers.addChildNode(node)
        }
    }

    static let ringImage: UIImage = UIGraphicsImageRenderer(size: CGSize(width: 64, height: 64)).image { ctx in
        UIColor(hex: 0xFF8A4C).setStroke()
        ctx.cgContext.setLineWidth(4)
        ctx.cgContext.strokeEllipse(in: CGRect(x: 6, y: 6, width: 52, height: 52))
    }

    static func label(_ text: String) -> UIImage {
        let font = UIFont.systemFont(ofSize: 34, weight: .bold)
        let attrs: [NSAttributedString.Key: Any] = [.font: font, .foregroundColor: UIColor.white]
        let size = (text as NSString).size(withAttributes: attrs)
        let pad: CGFloat = 18
        let canvas = CGSize(width: size.width + pad * 2, height: size.height + pad)
        return UIGraphicsImageRenderer(size: canvas).image { _ in
            UIColor(hex: 0xFF8A4C).setFill()
            UIBezierPath(roundedRect: CGRect(origin: .zero, size: canvas), cornerRadius: canvas.height / 2).fill()
            (text as NSString).draw(at: CGPoint(x: pad, y: pad / 2), withAttributes: attrs)
        }
    }

    // MARK: Ambient motion

    private var ambientOn: Bool?

    func setAmbientMotion(_ on: Bool) {
        guard ambientOn != on else { return }
        ambientOn = on
        keyLight.removeAllActions()
        guard on else { return }
        let sway = SCNAction.sequence([
            .rotateTo(x: -0.5, y: 0.6, z: 0, duration: 4.5, usesShortestUnitArc: true),
            .rotateTo(x: -0.5, y: -0.6, z: 0, duration: 4.5, usesShortestUnitArc: true),
        ])
        sway.timingMode = .easeInEaseOut
        keyLight.runAction(.repeatForever(sway))
    }

    // MARK: Input

    func handleTap(at point: CGPoint) {
        guard let view else { return }
        let hits = view.hitTest(point, options: [.searchMode: SCNHitTestSearchMode.all.rawValue, .ignoreHiddenNodes: true])
        for hit in hits {
            var node: SCNNode? = hit.node
            while let n = node, n !== scene.rootNode {
                if n.parent === markers, let id = n.name {
                    onMarker?(id)
                    return
                }
                node = n.parent
            }
        }
        guard let hit = hits.first(where: { $0.node === skinNode || $0.node === muscleNode || $0.node === headNode }) else { return }
        if hit.node === headNode {
            onSelect?(.head, nil)
            return
        }
        let layerData = hit.node === muscleNode ? model.muscle : model.skin
        guard let picked = model.lookup(layerData, element: hit.geometryIndex, face: hit.faceIndex) else { return }
        // On the muscle layer the face is the smooth head; its muscles are never picked on their own.
        if hit.node === muscleNode, headNode.geometry != nil, picked.0 == .head || picked.1?.bodyRegion == .head {
            onSelect?(.head, nil)
            return
        }
        onSelect?(picked.0, picked.1)
    }
}

// MARK: - SwiftUI wrapper

struct BodySceneView: UIViewRepresentable {
    let controller: BodySceneController
    var animate: Bool

    func makeUIView(context: Context) -> SCNView {
        let v = SCNView(frame: .zero, options: [SCNView.Option.preferredRenderingAPI.rawValue: SCNRenderingAPI.metal.rawValue])
        v.scene = controller.scene
        v.pointOfView = controller.cameraNode
        v.backgroundColor = .clear
        v.antialiasingMode = .multisampling4X
        v.preferredFramesPerSecond = 60
        v.isPlaying = true
        v.rendersContinuously = animate
        v.accessibilityLabel = "3D body. Drag sideways to turn, pinch to zoom, tap a muscle or region."
        controller.view = v

        let pan = UIPanGestureRecognizer(target: context.coordinator, action: #selector(Coordinator.pan(_:)))
        pan.delegate = context.coordinator
        v.addGestureRecognizer(pan)
        v.addGestureRecognizer(UIPinchGestureRecognizer(target: context.coordinator, action: #selector(Coordinator.pinch(_:))))
        v.addGestureRecognizer(UITapGestureRecognizer(target: context.coordinator, action: #selector(Coordinator.tap(_:))))
        return v
    }

    func updateUIView(_ v: SCNView, context: Context) {
        v.rendersContinuously = animate
        controller.setAmbientMotion(animate)
    }

    func makeCoordinator() -> Coordinator { Coordinator(controller: controller) }

    @MainActor
    final class Coordinator: NSObject, UIGestureRecognizerDelegate {
        let controller: BodySceneController
        init(controller: BodySceneController) { self.controller = controller }

        @objc func pan(_ g: UIPanGestureRecognizer) {
            if g.state == .began { controller.onInteract?() }
            let dx = Float(g.translation(in: g.view).x)
            g.setTranslation(.zero, in: g.view)
            controller.rotate(by: dx * 0.011)
            if g.state == .ended {
                let v = Float(g.velocity(in: g.view).x) * 0.0022
                controller.setYaw(BodySceneController.snapped(controller.yaw + max(-2.5, min(2.5, v))))
            }
        }

        @objc func pinch(_ g: UIPinchGestureRecognizer) {
            if g.state == .began { controller.onInteract?() }
            controller.zoom(by: Float(g.scale))
            g.scale = 1
        }

        @objc func tap(_ g: UITapGestureRecognizer) {
            controller.onInteract?()
            controller.handleTap(at: g.location(in: g.view))
        }

        /// Only horizontal drags turn the figure, so vertical drags keep scrolling the page.
        func gestureRecognizerShouldBegin(_ g: UIGestureRecognizer) -> Bool {
            guard let pan = g as? UIPanGestureRecognizer else { return true }
            let v = pan.velocity(in: pan.view)
            return abs(v.x) > abs(v.y)
        }
    }
}
